don't kill all descriptors when looking for new Characteristics
Previously when looking for characteristics, all descriptors of the
related service were deleted. This caused a bug when messages on one of
the descriptors arrived before the descriptors were rediscovered. This
should fix it. Fixed the following Bug for me
TypeError: Cannot set property '2902' of undefined
at null.<anonymous>
(/root/node/node_modules/noble/lib/hci-socket/gatt.js:608:81)
at Gatt.onAclStreamData
(/root/node/node_modules/noble/lib/hci-socket/gatt.js:122:26)
at emitTwo (events.js:92:20)
at emit (events.js:172:7)
at AclStream.push
(/root/node/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
at NobleBindings.onAclDataPkt
(/root/node/node_modules/noble/lib/hci-socket/bindings.js:263:15)
at emitThree (events.js:97:13)
at emit (events.js:175:7)
at Hci.onSocketData
(/root/node/node_modules/noble/lib/hci-socket/hci.js:447:14)
at emitOne (events.js:77:13)